// Generated by `pnpm --filter @digihostel/api-spec run codegen` from packages/api-spec/openapi.yaml.
// Do not hand-edit ./generated — fix the OpenAPI source and regenerate (.claude/rules/coding.md).
export * from "./generated/api.js";
export * from "./custom-fetch.js";
