/**
 * Static trusted-device education copy (Prompt 4B) — the single source for
 * both the inline explainer on the onboarding registration screen
 * (`app/(onboarding)/devices.tsx`) and the standalone Security Tips screen
 * (`app/(app)/security/tips.tsx`), so the two never drift apart.
 *
 * Deliberately plain language, no cryptographic/attestation terminology
 * (the SDD does not require exposing implementation detail to the user —
 * see docs/authentication.md §15's security-UX rationale) and no invented
 * claim this app can't back up — see `SECURITY_UX_RULES` in that same doc.
 */

import type { InfoSection } from "../../types/content";

/** @deprecated import `InfoSection` from `src/types/content` directly — kept
 * as an alias so this module's existing named export isn't a breaking
 * change for any other in-progress work. */
export type DeviceInfoSection = InfoSection;

export const DEVICE_REGISTRATION_SECTIONS: InfoSection[] = [
  {
    title: "Why does this device need to be verified?",
    body: "Verifying your device helps confirm that leave approvals for your child are really coming from you, not someone else who happens to have your password.",
  },
  {
    title: "How does this help protect your account?",
    body: "Once a device is trusted, it becomes part of how we recognize you. An unrecognized device can't approve or reject a leave request on your behalf.",
  },
  {
    title: "What is stored?",
    body: "Only a random identifier generated by this app, your device's platform (iOS or Android), and the date it was registered.",
  },
  {
    title: "What is not stored?",
    body: "We never collect your device's serial number, IMEI, MAC address, or any other hardware identifier. Nothing about you personally is stored beyond your existing parent account.",
  },
  {
    title: "What happens after verification?",
    body: "Once verified, this device can be used to review and approve your child's leave requests.",
  },
  {
    title: "What happens if verification fails?",
    body: "You can try again at any time. Your account itself is never at risk — an unverified device simply can't approve leave requests yet.",
  },
];

export const DEVICE_SECURITY_TIPS: DeviceInfoSection[] = [
  {
    title: "Keep your device secure",
    body: "Use a screen lock (PIN, pattern, or biometric) on any device you use to approve leave requests.",
  },
  {
    title: "Remove devices you no longer use",
    body: "If you replace your phone or no longer use a device, remove it from your trusted device list.",
  },
  {
    title: "Review your devices periodically",
    body: "Check your trusted device list from time to time to make sure you recognize every device on it.",
  },
  {
    title: "Something looks wrong?",
    body: "If you see a device you don't recognize, remove it and contact the hostel administration.",
  },
];
